### PR TITLE
small modifications

### PR DESCRIPTION
**Pull request by LinguList**
basically, only the documentation, and a new way to add matrices initially in plot_heatmap function.

### CODE REVIEW

**Comment by LinguList** [comment]
I just realized, that there is still one error.log file written to the tests/ not to tests/output/, but I have no idea why. I ran nosetests from within tests/...

**Comment by xrotwang** [comment]
hm. cannot confirm. This should show up in `git status`, right? AFAICT it would not be hidden by `.gitignore`.

**Comment by LinguList** [comment]
yes, that's how I detected it, since it popped up in "git status"...

**Comment by LinguList** [comment]
okay, false alarm, don't ask me what I was seeing there... Maybe I just
forgot to remove a relic...

**Pull request merged**
