### PR TITLE
Minor refactor

### PR DESCRIPTION
**Pull request by SimonGreenhill**

### CODE REVIEW

**Comment by LinguList** [comment]
This passes the checks, but the `CT_` values are important for the weight calculation, or are they in fact obsolete?

**Comment by SimonGreenhill** [comment]
These are just duplicate dictionary keys, so they should be getting overwritten immediately when the dict is defined, and not visible to the rest of the code, right?

**Comment by LinguList** [comment]
sure, sorry, did only look at the github for the diff... didn't see they are duplicates (how embarassing...)

**Comment by SimonGreenhill** [comment]
I've been playing around with http://codefactor.io which is great for spotting these things!

**Pull request merged**
