### PR TITLE
fix pathlib in wl2qlc

### PR DESCRIPTION
**Pull request by SimonGreenhill**
`wl2qlc` fails if given a pathlib instance. This PR makes it work.

```
Traceback (most recent call last):
...
  File "/Users/simon/.pyenv/versions/3.9.6/lib/python3.9/site-packages/lingpy-2.6.9-py3.9.egg/lingpy/basic/wordlist.py", line 921, in output
    return self._output(fileformat, **keywords)
  File "/Users/simon/.pyenv/versions/3.9.6/lib/python3.9/site-packages/lingpy-2.6.9-py3.9.egg/lingpy/basic/wordlist.py", line 772, in _output
    return wl2qlc(header, out, **keywords)
  File "/Users/simon/.pyenv/versions/3.9.6/lib/python3.9/site-packages/lingpy-2.6.9-py3.9.egg/lingpy/basic/ops.py", line 453, in wl2qlc
    filename + '.' + keywords['fileformat'],
TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'
```

### CODE REVIEW

**Review by xrotwang — APPROVED** [review]

**Comment by LinguList** [comment]
Should we adjust our tox.ini before merging?

**Comment by xrotwang** [comment]
I already did in master.

**Comment by xrotwang** [comment]
Dunno where the "build (3.5/6) Expected" checks come from. https://github.com/lingpy/lingpy/pull/441/checks only lists 4.

**Comment by SimonGreenhill** [comment]
weird, looks like it's got the old tox.ini -- perhaps pushing something else here will retrigger the tests?

**Comment by xrotwang** [comment]
I'd just merge and see what happens in master.

**Pull request merged**
