### PR TITLE
Compatibility with igraph 0.10.5 (and presumably 0.11)

### PR DESCRIPTION
**Pull request by xrotwang**
Supersedes #448

### CODE REVIEW

**Comment by xrotwang** [comment]
I kept this PR minimal (and somewhat hacky), because I think a more complete analysis of the issue should only be done once we modernized the code base (dropped py3.7 compat, updated packaging, ...)

**Comment by LinguList** [comment]
I agree. This is perfect for now.

**Review by LinguList — APPROVED** [review]

**Comment by LinguList** [comment]
In fact, the use of integers as ID here was in part forced or forced by my false thinking of the way node identifiers are handled in igraph. This was never really clear to me, but if you load a graph in igraph, it has (had) the numerical ID per node, while networkx always uses node label (also when reading from gml). It looked convenient in the settings used here, in the past, but in the retrospective, integration of igraph was always a bit hacky.

**Comment by LinguList** [comment]
Many thanks, @xrotwang !

**Pull request merged**
