### PR TITLE
Load cldf

### PR DESCRIPTION
**Pull request by Anaphory**
Adresses #369, but not the more detailed tests mentioned there.

### CODE REVIEW

**Comment by xrotwang** [comment]
Hm. Is there a good reason to merge a PR when CI still fails?

**Comment by LinguList** [comment]
See the issue #376

**Comment by LinguList** [comment]
It was a mistake, but as to #376: @Anaphory, I don't see a reason to actually change the settings. Some people have write access and can push to master, some haven't, they can't. We gave you write access, but we could also revoke it, if you prefer. Protection is not what I'd like.

**Comment by LinguList** [comment]
And I'd even not know how to do it ...

**Comment by LinguList** [comment]
BTW2: @Anaphory, to fix the FileNotFoundError, just grep in lingpy, we have a workaround for that, I'm sure.

**Comment by Anaphory** [comment]
> BTW2: @Anaphory, to fix the FileNotFoundError, just grep in lingpy, we have a workaround for that, I'm sure.

The issue was less that I didn't know how to deal with it, and more that I had forgotten that I was looking for an error I explicitly raised myself, so I had to change two spots. (But yes, using `compat` looks like a more consistent solution.)

**Comment by LinguList** [comment]
> Protecting the branch seems to be straightforward: https://help.github.com/articles/configuring-protected-branches/
But generally, I'd agree to "with great power comes great responsibility". Maybe, though, lingpy is mature enough a project to enforce stricter policies, e.g. "no code enters the master branch without code review" - i.e. only through PR?

I agree with this. Is it easy to set it up?

**Comment by xrotwang** [comment]
So, what I just configured is: The master branch can only be changed by
- merging pull requests
- which pass Travis CI
- and have at least one approving review

Let's see whether this is too strict, and inhibiting fast progress. Ideally, I think, this is what we want. There should be enough lingpy committers now, to make it possible to only merge code that has been looked at by two people.

**Comment by LinguList** [comment]
BTW: @Anaphory, you should be part of the "with contributions by" list in the next release (probably first a bugfix with 2.6.5 or so, later then 2.7). If you introduce more, you can even make it into our editorial board :)

**Comment by tresoldi** [comment]
Sounds good to me, too. For the ngram module we already had this in a way, with Travis and 99% coverage of the new code, a PR, @LinguList formally reviewing/approving and @xrotwang more informally.

**Comment by xrotwang** [comment]
Yes, I think with 7 people having write access, reviewing shouldn't be a bottleneck.

**Pull request merged**
